version: "3.7"

services:
  project:
    restart: always
    build: ./project
    container_name: project
    expose:
      - 8001
    volumes:
      - ./project:/app
    environment:
      - TZ=Asia/Taipei
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - project
    environment:
      - TZ=Asia/Taipei
